version: "3.9"

services:
  app:
    build: .
    container_name: sporta-calendar-backend
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules
    command:
      sh -c "npx prisma migrate deploy --schema=src/prisma/schema.prisma &&
      /app/node_modules/.bin/nodemon --legacy-watch /app/src/index.js"
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    container_name: sporta-postgres-db
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - back-tier

volumes:
  postgres-data:

networks:
  back-tier:
    driver: bridge
